# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Dimitris Glezos <glezos@transifex.com>, 2011
# Hajime Taira <htaira@redhat.com>, 2011
# hyuugabaru <hyu_gabaru@yahoo.co.jp>, 2009
# Kiyoto Hashida <khashida@redhat.com>, 2008, 2009, 2010
# Kiyoto Hashida <khashida@redhat.com>, 2006, 2007
# noriko <noriko@fedoraproject.org>, 2013
# Noriko Mizumoto <noriko@redhat.com>, 2006, 2008
# Tomoyuki KATO <tomo@dream.daynight.jp>, 2011-2013
# 高一人参 @欠陥遺伝子 <www.carrotsoft@gmail.com>, 2011
# Noriko Mizumoto <noriko@redhat.com>, 2016. #zanata
# Vit Mojzis <vmojzis@redhat.com>, 2017. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-10-31 20:57+0100\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2017-09-01 08:30-0400\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language-Team: Japanese (http://www.transifex.com/projects/p/fedora/language/"
"ja/)\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Zanata 3.9.6\n"

#: ../setroubleshoot.desktop.in.h:1
msgid "SELinux Troubleshooter"
msgstr "SELinux Troubleshooter"

#: ../setroubleshoot.desktop.in.h:2
msgid "Troubleshoot SELinux access denials"
msgstr "SELinux アクセス拒否のトラブルシューティング"

#: ../setroubleshoot.desktop.in.h:3
msgid "policy;security;selinux;avc;permission;mac;alert;sealert;"
msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"

#: ../src/setroubleshoot/audit_data.py:912
#, python-format
msgid "port %s"
msgstr "ポート %s"

#: ../src/setroubleshoot/audit_data.py:914 ../src/setroubleshoot/browser.py:759
#: ../src/setroubleshoot/browser.py:834 ../src/setroubleshoot/rpc.py:528
#: ../src/setroubleshoot/util.py:242
msgid "Unknown"
msgstr "不明"

#: ../src/setroubleshoot/audit_data.py:1004
#, python-format
msgid "%s \n"
"**** Invalid AVC allowed in current policy ***\n"
msgstr "%s \n"
"**** 無効な AVC が現在のポリシーで許可されています ***\n"

#: ../src/setroubleshoot/audit_data.py:1006
#, python-format
msgid ""
"%s \n"
"**** Invalid AVC dontaudited in current policy.  'semodule -B' will turn on "
"dontaudit rules. ***\n"
msgstr ""
"%s \n"
"**** 無効な AVC が現在のポリシーで dontaudit されています。  'semodule -B' が dontaudit "
"ルールをオンにします。 ***\n"

#: ../src/setroubleshoot/audit_data.py:1008
msgid "Must call policy_init first"
msgstr "policy_init を最初にコールしなければなりません"

#: ../src/setroubleshoot/audit_data.py:1010
#, python-format
msgid "%s \n"
"**** Invalid AVC bad target context. ***\n"
msgstr "%s \n"
"**** 無効な AVC 不正ターゲットコンテキストです。 ***\n"

#: ../src/setroubleshoot/audit_data.py:1012
#, python-format
msgid "%s \n"
"**** Invalid AVC bad source context. ***\n"
msgstr "%s \n"
"**** 無効な AVC 不正ソースコンテキストです。 ***\n"

#: ../src/setroubleshoot/audit_data.py:1014
#, python-format
msgid "%s \n"
"**** Invalid AVC bad type class ***\n"
msgstr "%s \n"
"**** 無効な AVC 不正タイプクラスです ***\n"

#: ../src/setroubleshoot/audit_data.py:1016
#, python-format
msgid "%s \n"
"**** Invalid AVC bad permission ***\n"
msgstr "%s \n"
"**** 無効な AVC 不正認可です ***\n"

#: ../src/setroubleshoot/audit_data.py:1018
msgid "Error during access vector computation"
msgstr "アクセスベクターの演算時にエラーが発生しました"

#: ../src/setroubleshoot/browser.py:183 ../gui/browser.glade.h:14
msgid "SELinux Alert Browser"
msgstr "SELinux 通知ブラウザー"

#: ../src/setroubleshoot/browser.py:187 ../gui/browser.glade.h:21
msgid "The source process:"
msgstr "原因プロセス:"

#: ../src/setroubleshoot/browser.py:192 ../gui/browser.glade.h:17
msgid "Yes"
msgstr "はい"

#: ../src/setroubleshoot/browser.py:194 ../gui/browser.glade.h:19
msgid "No"
msgstr "いいえ"

#: ../src/setroubleshoot/browser.py:199 ../gui/browser.glade.h:22
msgid "Attempted this access:"
msgstr "試行したアクセス:"

#: ../src/setroubleshoot/browser.py:213 ../gui/browser.glade.h:12
msgid "SETroubleshoot Details Window"
msgstr "SETroubleshootの詳細のウィンドウ"

#: ../src/setroubleshoot/browser.py:216 ../gui/browser.glade.h:16
msgid "Would you like to receive alerts?"
msgstr "通知を受け取りますか？"

#: ../src/setroubleshoot/browser.py:220 ../gui/browser.glade.h:26
msgid "Notify Admin"
msgstr "管理者に通知"

#: ../src/setroubleshoot/browser.py:223 ../src/setroubleshoot/browser.py:229
#: ../gui/browser.glade.h:8
msgid "Troubleshoot"
msgstr "トラブルシュート"

#: ../src/setroubleshoot/browser.py:226 ../gui/browser.glade.h:28
msgid "Details"
msgstr "詳細"

#: ../src/setroubleshoot/browser.py:233 ../gui/browser.glade.h:7
msgid "SETroubleshoot Alert List"
msgstr "SETroubleshoot 通知リスト"

#: ../src/setroubleshoot/browser.py:235 ../gui/browser.glade.h:37
msgid "List All Alerts"
msgstr "すべての通知の一覧"

#: ../src/setroubleshoot/browser.py:282
msgid "#"
msgstr "#"

#: ../src/setroubleshoot/browser.py:282
msgid "Source Process"
msgstr "ソースプロセス"

#: ../src/setroubleshoot/browser.py:282
msgid "Attempted Access"
msgstr "試行したアクセス"

#: ../src/setroubleshoot/browser.py:282
msgid "On this"
msgstr "試行の対象"

#: ../src/setroubleshoot/browser.py:282
msgid "Occurred"
msgstr "発生回数"

#: ../src/setroubleshoot/browser.py:282
msgid "Status"
msgstr "ステータス"

#: ../src/setroubleshoot/browser.py:356 ../src/setroubleshoot/browser.py:798
#: ../src/setroubleshoot/browser.py:842
msgid "Notify"
msgstr "通知する"

#: ../src/setroubleshoot/browser.py:357
msgid "Notify alert in the future."
msgstr "後ほど警告を表示します。"

#: ../src/setroubleshoot/browser.py:360 ../src/setroubleshoot/browser.py:800
#: ../src/setroubleshoot/browser.py:840 ../gui/browser.glade.h:29
msgid "Ignore"
msgstr "無視"

#: ../src/setroubleshoot/browser.py:361 ../gui/browser.glade.h:30
msgid "Ignore alert in the future."
msgstr "次回から警告を無視します。"

#: ../src/setroubleshoot/browser.py:397
msgid "<b>If you were trying to...</b>"
msgstr "<b>次を試行していた場合...</b>"

#: ../src/setroubleshoot/browser.py:406
msgid "<b>Then this is the solution.</b>"
msgstr "<b>これが解決策です</b>"

#: ../src/setroubleshoot/browser.py:513
msgid "Plugin\n"
"Details"
msgstr "プラグイン\n"
"詳細"

#: ../src/setroubleshoot/browser.py:528
msgid "Report\n"
"Bug"
msgstr "バグ\n"
"報告"

#: ../src/setroubleshoot/browser.py:556
#, python-format
msgid "Plugin: %s "
msgstr "プラグイン: %s "

#: ../src/setroubleshoot/browser.py:623
msgid "Unable to grant access."
msgstr "アクセスを認可できません"

#: ../src/setroubleshoot/browser.py:654 ../src/setroubleshoot/browser.py:796
#, python-format
msgid "Alert %d of %d"
msgstr "通知 %d / %d"

#: ../src/setroubleshoot/browser.py:779
#, python-format
msgid "On this %s:"
msgstr "対象 %s:"

#: ../src/setroubleshoot/browser.py:827 ../src/setroubleshoot/browser.py:833
#: ../src/setroubleshoot/signature.py:404
msgid "N/A"
msgstr "N/A"

#: ../src/setroubleshoot/browser.py:874 ../src/setroubleshoot/browser.py:875
#: ../gui/browser.glade.h:34
msgid "No Alerts"
msgstr "通知なし"

#: ../src/setroubleshoot/browser.py:893
msgid "SELinux has detected a problem."
msgstr "SELinux は問題を検出しました。"

#: ../src/setroubleshoot/browser.py:999
msgid "Sealert Error"
msgstr "Sealert エラー"

#: ../src/setroubleshoot/browser.py:1010
msgid "Sealert Message"
msgstr "Sealert メッセージ"

#. -----------------------------------------------------------------------------
#: ../src/setroubleshoot/errcode.py:79
msgid "signature not found"
msgstr "署名が見つかりませんでした"

#: ../src/setroubleshoot/errcode.py:80
msgid "multiple signatures matched"
msgstr "複数の署名が一致しました"

#: ../src/setroubleshoot/errcode.py:81
msgid "id not found"
msgstr "ID が見つかりませんでした"

#: ../src/setroubleshoot/errcode.py:82
msgid "database not found"
msgstr "データベースが見つかりませんでした"

#: ../src/setroubleshoot/errcode.py:83
msgid "item is not a member"
msgstr "アイテムはメンバーではありません"

#: ../src/setroubleshoot/errcode.py:84
msgid "illegal to change user"
msgstr "ユーザーの変更は不正です"

#: ../src/setroubleshoot/errcode.py:85
msgid "method not found"
msgstr "メソッドが見つかりませんでした"

#: ../src/setroubleshoot/errcode.py:86
msgid "cannot create GUI"
msgstr "GUI を作成できません"

#: ../src/setroubleshoot/errcode.py:87
msgid "value unknown"
msgstr "値が不明です"

#: ../src/setroubleshoot/errcode.py:88
msgid "cannot open file"
msgstr "ファイルを開けません"

#: ../src/setroubleshoot/errcode.py:89
msgid "invalid email address"
msgstr "無効な電子メールアドレス"

#. gobject IO Errors
#: ../src/setroubleshoot/errcode.py:92
msgid "socket error"
msgstr "ソケットエラー"

#: ../src/setroubleshoot/errcode.py:93
msgid "connection has been broken"
msgstr "接続が遮断されました"

#: ../src/setroubleshoot/errcode.py:94
msgid "Invalid request. The file descriptor is not open"
msgstr "無効な要求です。ファイル記述子は開いていません"

#: ../src/setroubleshoot/errcode.py:96
msgid "insufficient permission to modify user"
msgstr "ユーザーを変更するのに十分な権限がありません。"

#: ../src/setroubleshoot/errcode.py:97
msgid "authentication failed"
msgstr "認証は失敗しました"

#: ../src/setroubleshoot/errcode.py:98
msgid "user prohibited"
msgstr "ユーザーは禁止されています。"

#: ../src/setroubleshoot/errcode.py:99
msgid "not authenticated"
msgstr "認証されていません"

#: ../src/setroubleshoot/errcode.py:100
msgid "user lookup failed"
msgstr "ユーザーの検索に失敗しました"

#: ../src/setroubleshoot/gui_utils.py:53 ../src/sealert:539
#, c-format, python-format
msgid "Opps, %s hit an error!"
msgstr "%s  がエラーです!"

#: ../src/setroubleshoot/gui_utils.py:55 ../gui/fail_dialog.glade.h:1
msgid "Error"
msgstr "エラー"

#: ../src/setroubleshoot/Plugin.py:90
msgid ""
"If you want to allow $SOURCE_BASE_PATH to have $ACCESS access on the "
"$TARGET_BASE_PATH $TARGET_CLASS"
msgstr ""

#: ../src/setroubleshoot/server.py:214
#, python-format
msgid " For complete SELinux messages run: sealert -l %s"
msgstr ""

#: ../src/setroubleshoot/server.py:401
#, python-format
msgid "The user (%s) cannot modify data for (%s)"
msgstr "ユーザー(%s) は (%s) 用のデータを修正できません。"

#: ../src/setroubleshoot/server.py:465 ../src/sealert:299
msgid "Started"
msgstr "開始済み"

#: ../src/setroubleshoot/server.py:663
msgid "AVC"
msgstr "AVC"

#: ../src/setroubleshoot/server.py:729
msgid "Audit Listener"
msgstr "リスナーの監査"

#: ../src/setroubleshoot/signature.py:80
msgid "Never Ignore"
msgstr "無視しない"

#: ../src/setroubleshoot/signature.py:81
msgid "Ignore Always"
msgstr "常に無視する"

#: ../src/setroubleshoot/signature.py:82
msgid "Ignore After First Alert"
msgstr "最初の通知以後は無視"

#: ../src/setroubleshoot/signature.py:199
msgid "directory"
msgstr "ディレクトリ"

#: ../src/setroubleshoot/signature.py:200
msgid "semaphore"
msgstr "セマフォ"

#: ../src/setroubleshoot/signature.py:201
msgid "shared memory"
msgstr "共有メモリー"

#: ../src/setroubleshoot/signature.py:202
msgid "message queue"
msgstr "メッセージキュー"

#: ../src/setroubleshoot/signature.py:203
msgid "message"
msgstr "メッセージ"

#: ../src/setroubleshoot/signature.py:204
msgid "file"
msgstr "ファイル"

#: ../src/setroubleshoot/signature.py:205
msgid "socket"
msgstr "ソケット"

#: ../src/setroubleshoot/signature.py:206
msgid "process"
msgstr "プロセス"

#: ../src/setroubleshoot/signature.py:207
msgid "process2"
msgstr ""

#: ../src/setroubleshoot/signature.py:208
msgid "filesystem"
msgstr "ファイルシステム"

#: ../src/setroubleshoot/signature.py:209
msgid "node"
msgstr "ノード"

#: ../src/setroubleshoot/signature.py:210
msgid "capability"
msgstr "能力"

#: ../src/setroubleshoot/signature.py:211
msgid "capability2"
msgstr ""

#: ../src/setroubleshoot/signature.py:388
#, python-format
msgid "%s has a permissive type (%s). This access was not denied."
msgstr "%s は許容タイプ (%s) を持ちます。このアクセスは拒否されませんでした。"

#: ../src/setroubleshoot/signature.py:391
msgid "SELinux is in permissive mode. This access was not denied."
msgstr "SELinuxはpermissiveモードです。このアクセスは拒否されませんでした。"

#: ../src/setroubleshoot/signature.py:445
#, python-format
msgid "SELinux is preventing %s from using the %s access on a process."
msgstr "SELinux により %s がプロセスにおいて %s アクセスを使用できません"

#: ../src/setroubleshoot/signature.py:445
#, python-format
msgid "SELinux is preventing %s from using the '%s' accesses on a process."
msgstr "SELinux により %s がプロセスにおいて '%s' アクセスを使用できません"

#: ../src/setroubleshoot/signature.py:448
#, python-format
msgid "SELinux is preventing %s from using the %s capability."
msgstr "SELinux により %s が %s 能力を使用できません"

#: ../src/setroubleshoot/signature.py:448
#, python-format
msgid "SELinux is preventing %s from using the '%s' capabilities."
msgstr "SELinux により %s が '%s' 能力を使用できません"

#: ../src/setroubleshoot/signature.py:450
#, python-format
msgid "SELinux is preventing %s from %s access on the %s labeled %s."
msgstr "SELinux で %s による %s アクセスが %s ラベルの付いた %s では行えない設定になっています。"

#: ../src/setroubleshoot/signature.py:450
#, python-format
msgid "SELinux is preventing %s from '%s' accesses on the %s labeled %s."
msgstr "SELinux により %s が '%s' アクセスを %s のラベルがついた %s で拒否されました。"

#: ../src/setroubleshoot/signature.py:451
#, python-format
msgid "SELinux is preventing %s from %s access on the %s %s."
msgstr "SELinux により %s が %s アクセスを %s %s においてできません"

#: ../src/setroubleshoot/signature.py:451
#, python-format
msgid "SELinux is preventing %s from '%s' accesses on the %s %s."
msgstr "SELinux により %s が '%s' アクセスを %s %s においてできません"

#: ../src/setroubleshoot/signature.py:483
msgid "Additional Information:\n"
msgstr "追加情報:\n"

#: ../src/setroubleshoot/signature.py:484
msgid "Source Context"
msgstr "ソースコンテキスト"

#: ../src/setroubleshoot/signature.py:485
msgid "Target Context"
msgstr "ターゲットコンテキスト"

#: ../src/setroubleshoot/signature.py:486
msgid "Target Objects"
msgstr "ターゲットオブジェクト"

#: ../src/setroubleshoot/signature.py:487
msgid "Source"
msgstr "ソース"

#: ../src/setroubleshoot/signature.py:488
msgid "Source Path"
msgstr "ソースパス"

#: ../src/setroubleshoot/signature.py:489
msgid "Port"
msgstr "ポート"

#: ../src/setroubleshoot/signature.py:491
#: ../src/setroubleshoot/signature.py:493
msgid "Host"
msgstr "ホスト"

#: ../src/setroubleshoot/signature.py:494
msgid "Source RPM Packages"
msgstr "ソース RPM パッケージ"

#: ../src/setroubleshoot/signature.py:495
msgid "Target RPM Packages"
msgstr "ターゲット RPM パッケージ"

#: ../src/setroubleshoot/signature.py:496
msgid "Policy RPM"
msgstr "ポリシー RPM"

#: ../src/setroubleshoot/signature.py:497
msgid "Selinux Enabled"
msgstr "Selinux 有効化"

#: ../src/setroubleshoot/signature.py:498
msgid "Policy Type"
msgstr "ポリシータイプ"

#: ../src/setroubleshoot/signature.py:499
msgid "Enforcing Mode"
msgstr "強制モード"

#: ../src/setroubleshoot/signature.py:501
#: ../src/setroubleshoot/signature.py:503
msgid "Host Name"
msgstr "ホスト名"

#: ../src/setroubleshoot/signature.py:508
#: ../src/setroubleshoot/signature.py:510
msgid "Platform"
msgstr "プラットフォーム"

#: ../src/setroubleshoot/signature.py:511
msgid "Alert Count"
msgstr "通知カウント"

#: ../src/setroubleshoot/signature.py:513
msgid "First Seen"
msgstr "最初の画面"

#: ../src/setroubleshoot/signature.py:514
msgid "Last Seen"
msgstr "最後の画面"

#: ../src/setroubleshoot/signature.py:515
msgid "Local ID"
msgstr "ローカル ID"

#: ../src/setroubleshoot/signature.py:517
msgid "Raw Audit Messages"
msgstr "生の監査メッセージ"

#: ../src/setroubleshoot/signature.py:571
#, python-format
msgid "\n"
"\n"
"*****  Plugin %s (%.4s confidence) suggests   "
msgstr "\n"
"\n"
"*****  プラグイン %s (%.4s 信頼性) による示唆"

#: ../src/setroubleshoot/signature.py:574
msgid "*"
msgstr "*"

#: ../src/setroubleshoot/signature.py:575
#: ../src/setroubleshoot/signature.py:577
msgid "\n"
msgstr "\n"

#: ../src/setroubleshoot/signature.py:579
msgid "\n"
"Then "
msgstr "\n"
"このようにします: "

#: ../src/setroubleshoot/signature.py:582
msgid "\n"
"Do\n"
msgstr "\n"
"そして、以下を実行します: \n"

#: ../src/setroubleshoot/signature.py:584
msgid "\n"
"\n"
msgstr "\n"
"\n"

#: ../src/updater.py:18
#, python-format
msgid "current: %s "
msgstr "現在: %s"

#: ../src/updater.py:27
#, python-format
msgid "newer: %s "
msgstr "最新: %s"

#: ../src/seapplet.c:189
msgid "New SELinux security alert"
msgstr "新規の SELinux セキュリティ通知"

#: ../src/seapplet.c:189
msgid "AVC denial, click icon to view"
msgstr "AVC 拒否、アイコンをクリックして表示"

#: ../src/seapplet.c:195 ../src/seapplet.c:246
msgid "Dismiss"
msgstr "解除"

#: ../src/seapplet.c:205 ../src/seapplet.c:256
msgid "Show"
msgstr "表示"

#. set tooltip
#: ../src/seapplet.c:440 ../src/sealert:67
msgid "SELinux AVC denial, click to view"
msgstr "SELinux AVC 拒否、クリックして表示"

#: ../src/sealert:109
msgid "SELinux not enabled, sealert will not run on non SELinux systems"
msgstr "SELinux が有効化されていません。sealert は SELinux が有効なシステム以外では動作しません。"

#: ../src/sealert:156
msgid "Not fixable."
msgstr "修正不可です。"

#: ../src/sealert:163
#, c-format
msgid "Successfully ran %s"
msgstr "%s を正常に実行しました。"

#: ../src/sealert:170
#, c-format
msgid "Plugin %s not valid for %s id"
msgstr "プラグイン %s は %s id には認められていません。"

#: ../src/setroubleshootd:73
msgid "SELinux not enabled, setroubleshootd exiting..."
msgstr "SELinux が有効になっていません。setroubleshootd は終了します..."

#: ../src/setroubleshootd:105
#, c-format
msgid "fork #1 failed: %d (%s)"
msgstr "fork #1 は失敗です: %d (%s)"

#: ../gui/browser.glade.h:1
msgid ""
"Copyright (c) 2010 \n"
"Thomas Liu <tliu@redhat.com>\n"
"Máirín Duffy <duffy@redhat.com>\n"
"Daniel Walsh <dwalsh@redhat.com>\n"
"John Dennis <jdennis@redhat.com>\n"
msgstr ""
"Copyright (c) 2010 \n"
"Thomas Liu <tliu@redhat.com>\n"
"Máirín Duffy <duffy@redhat.com>\n"
"Daniel Walsh <dwalsh@redhat.com>\n"
"John Dennis <jdennis@redhat.com>\n"

#: ../gui/browser.glade.h:9
msgid "Troubleshoot selected alert"
msgstr "SETroubleshootが選択した警告"

#: ../gui/browser.glade.h:10
msgid "Delete"
msgstr ""

#: ../gui/browser.glade.h:11
msgid "Delete Selected Alerts"
msgstr "選択されたアラートを削除"

#: ../gui/browser.glade.h:13
msgid "Close"
msgstr ""

#: ../gui/browser.glade.h:15
msgid "<b>SELinux has detected a problem.</b>"
msgstr "<b>SELinux は問題を検出しました。</b>"

#: ../gui/browser.glade.h:18
msgid "Turn on alert pop-ups."
msgstr "通知のポップアップを有効化"

#: ../gui/browser.glade.h:20
msgid "Turn off alert pop-ups."
msgstr "通知のポップアップを無効化"

#: ../gui/browser.glade.h:23
msgid "On this file:"
msgstr "このファイル内:"

#: ../gui/browser.glade.h:24
msgid "label"
msgstr "label"

#: ../gui/browser.glade.h:25
msgid ""
"Read alert troubleshoot information.  May require administrative privileges "
"to remedy."
msgstr "トラブルシューティングに関する情報をお読みください。多くの場合、トラブルを解決するには、root権限が必要です。"

#: ../gui/browser.glade.h:27
msgid "Email alert to system administrator."
msgstr "Eメールでシステム管理者に通知"

#: ../gui/browser.glade.h:31
msgid "Delete current alert from the database."
msgstr "現在の通知をデータベースから削除"

#: ../gui/browser.glade.h:32
msgid "Previous"
msgstr ""

#: ../gui/browser.glade.h:33
msgid "Show previous alert."
msgstr "前の通知を表示"

#: ../gui/browser.glade.h:35
msgid "Next"
msgstr ""

#: ../gui/browser.glade.h:36
msgid "Show next alert."
msgstr "次の通知を表示"

#: ../gui/browser.glade.h:38
msgid "List all alerts in the database."
msgstr "データベースからすべての通知を一覧"

#: ../gui/bug_report.glade.h:1
msgid "Review and Submit Bug Report"
msgstr "確認とバグ報告の提出"

#: ../gui/bug_report.glade.h:2
msgid "<span size='large' weight='bold'>Review and Submit Bug Report</span>"
msgstr "<span size='large' weight='bold'>確認とバグ報告の提出</span>"

#: ../gui/bug_report.glade.h:3
msgid ""
"You may wish to review the error output that will be included in this bug "
"report and modify it to exclude any sensitive data below."
msgstr "このバグ報告に含まれるエラー出力を確認して、以下のような機密情報を排除するために それを修正すると良いでしょう。"

#: ../gui/bug_report.glade.h:4
msgid "Included error output:"
msgstr "含まれているエラー出力:"

#: ../gui/bug_report.glade.h:5
msgid "Submit Report"
msgstr "報告の提出"

#: ../gui/fail_dialog.glade.h:2 ../gui/success_dialog.glade.h:2
msgid ""
"This operation was completed.  The quick brown fox jumped over the lazy dog."
msgstr "このオプションは完了です。「素早い茶色の狐がのろまな犬を飛び越えました。」"

#: ../gui/success_dialog.glade.h:1
msgid "Success!"
msgstr "成功しました!"

#: ../gui/success_dialog.glade.h:3
msgid "button"
msgstr "ボタン"
